In [1]:
import pandas as pd
import numpy as np

In [5]:
df1 = pd.read_csv('D:\python statistic\data\OR107 grades.csv')

print('Head of dataset:')
display(df1.head())

print("Tail of dataset:")
display(df1.tail())

Head of dataset:

,student-id,Section,Case Assignment 1 (1579),Case Assignment 2 (1843),Case Assignment 3 (2014),Pre-lecture problems for Lecture 2 (1631),Pre-lecture problems for Lecture 3 (1683),Pre-lecture problems for Lecture 4 (1731),Pre-lecture problems for Lecture 5 (1779),Pre-lecture Problems for Lecture 6 (1811),Pre-lecture Problems for Lecture 7 (1877),Pre-lecture Problems for Lecture 9 (1942),Pre-lecture Problems for Lecture 10 (1990),Pre-lecture Problems for Lecture 11 (2025),Homework 1 (1776),Homework 2 (1928),Homework 3 (2103),Final project proposal (2125),Final project (2126),Final Exam (2231)
0,Points Possible,NaN,100.0,100.0,100.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,100.0,100.0,100.0,0.0,0.00,100.0
1,88,107-2 作業研究 Operations Research,72.0,NaN,NaN,NaN,9.0,NaN,8.0,10.0,NaN,NaN,NaN,NaN,82.0,NaN,NaN,NaN,NaN,NaN
2,89,107-2 作業研究 Operations Research,72.0,82.0,84.0,7.0,9.0,9.0,9.0,8.0,5.0,10.0,5.0,NaN,76.0,85.0,69.0,NaN,92.69,41.0
3,90,107-2 作業研究 Operations Research,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,91,107-2 作業研究 Operations Research,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Tail of dataset:

,student-id,Section,Case Assignment 1 (1579),Case Assignment 2 (1843),Case Assignment 3 (2014),Pre-lecture problems for Lecture 2 (1631),Pre-lecture problems for Lecture 3 (1683),Pre-lecture problems for Lecture 4 (1731),Pre-lecture problems for Lecture 5 (1779),Pre-lecture Problems for Lecture 6 (1811),Pre-lecture Problems for Lecture 7 (1877),Pre-lecture Problems for Lecture 9 (1942),Pre-lecture Problems for Lecture 10 (1990),Pre-lecture Problems for Lecture 11 (2025),Homework 1 (1776),Homework 2 (1928),Homework 3 (2103),Final project proposal (2125),Final project (2126),Final Exam (2231)
79,166,107-2 作業研究 Operations Research,69.0,86.0,100.0,10.0,9.0,8.0,10.0,10.0,NaN,10.0,8.0,8.0,100.0,78.0,93.0,NaN,94.76,70.0
80,167,107-2 作業研究 Operations Research,87.0,NaN,NaN,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,168,107-2 作業研究 Operations Research,72.0,90.0,97.0,9.0,10.0,10.0,10.0,10.0,10.0,10.0,9.0,9.0,98.0,95.0,89.0,NaN,94.61,75.0
82,169,107-2 作業研究 Operations Research,117.0,95.0,100.0,10.0,8.0,10.0,10.0,10.0,8.0,8.0,9.0,10.0,98.0,96.0,85.0,NaN,98.50,82.0
83,170,107-2 作業研究 Operations Research,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df1 = df1.fillna(0)
df1

,student-id,Section,Case Assignment 1 (1579),Case Assignment 2 (1843),Case Assignment 3 (2014),Pre-lecture problems for Lecture 2 (1631),Pre-lecture problems for Lecture 3 (1683),Pre-lecture problems for Lecture 4 (1731),Pre-lecture problems for Lecture 5 (1779),Pre-lecture Problems for Lecture 6 (1811),Pre-lecture Problems for Lecture 7 (1877),Pre-lecture Problems for Lecture 9 (1942),Pre-lecture Problems for Lecture 10 (1990),Pre-lecture Problems for Lecture 11 (2025),Homework 1 (1776),Homework 2 (1928),Homework 3 (2103),Final project proposal (2125),Final project (2126),Final Exam (2231)
0,Points Possible,0,100.0,100.0,100.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,100.0,100.0,100.0,0.0,0.00,100.0
1,88,107-2 作業研究 Operations Research,72.0,0.0,0.0,0.0,9.0,0.0,8.0,10.0,0.0,0.0,0.0,0.0,82.0,0.0,0.0,0.0,0.00,0.0
2,89,107-2 作業研究 Operations Research,72.0,82.0,84.0,7.0,9.0,9.0,9.0,8.0,5.0,10.0,5.0,0.0,76.0,85.0,69.0,0.0,92.69,41.0
3,90,107-2 作業研究 Operations Research,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
4,91,107-2 作業研究 Operations Research,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,166,107-2 作業研究 Operations Research,69.0,86.0,100.0,10.0,9.0,8.0,10.0,10.0,0.0,10.0,8.0,8.0,100.0,78.0,93.0,0.0,94.76,70.0
80,167,107-2 作業研究 Operations Research,87.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
81,168,107-2 作業研究 Operations Research,72.0,90.0,97.0,9.0,10.0,10.0,10.0,10.0,10.0,10.0,9.0,9.0,98.0,95.0,89.0,0.0,94.61,75.0
82,169,107-2 作業研究 Operations Research,117.0,95.0,100.0,10.0,8.0,10.0,10.0,10.0,8.0,8.0,9.0,10.0,98.0,96.0,85.0,0.0,98.50,82.0
83,170,107-2 作業研究 Operations Research,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0

In [12]:
df2 = [df1['student-id']]
df2 = pd.DataFrame(df2)
df2 = df2.T
df2 = df2.drop(df2.index[[0]])
df2['avg_week_result'] = 0 
df2

   student-id  avg_week_result
1          88                0
2          89                0
3          90                0
4          91                0
5          92                0
..        ...              ...
79        166                0
80        167                0
81        168                0
82        169                0
83        170                0

[83 rows x 2 columns]

In [22]:
for i in range(1,84):
    
             df2['avg_week_result'][i]= ( df1['Pre-lecture problems for Lecture 2 (1631)'][i] + df1['Pre-lecture problems for Lecture 3 (1683)'][i]+ df1['Pre-lecture problems for Lecture 4 (1731)'][i] + df1['Pre-lecture problems for Lecture 5 (1779)'][i] + df1['Pre-lecture Problems for Lecture 6 (1811)'][i] +df1['Pre-lecture Problems for Lecture 7 (1877)'][i] +df1['Pre-lecture Problems for Lecture 9 (1942)'][i] + df1['Pre-lecture Problems for Lecture 10 (1990)'][i] + df1['Pre-lecture Problems for Lecture 11 (2025)'][i] ) /9

C:\Users\dlkk9\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
pd.set_option('display.max_rows', df2.shape[0]+1)

In [24]:
df2

   student-id  avg_week_result
1          88                3
2          89                6
3          90                0
4          91                0
5          92                0
6          93                0
7          94                0
8          95                0
9          96                1
10         97                9
11         98                9
12         99                0
13        100                4
14        101                9
15        102                6
16        103                8
17        104                8
18        105                8
19        106                9
20        107                0
21        108                8
22        109                0
23        110                1
24        111                6
25        112                0
26        113                9
27        114                0
28        115                2
29        116                9
30        117                8
31        118                8
32        119                7
33        120                2
34        121                0
35        122                0
36        123                8
37        124                0
38        125                6
39        126                0
40        127                2
41        128                9
42        129                8
43        130                0
44        131                9
45        132                0
46        133                7
47        134                7
48        135                8
49        136                3
50        137                8
51        138                5
52        139                6
53        140                8
54        141                9
55        142                0
56        143                0
57        144                0
58        145                8
59        146                6
60        147                9
61        148                9
62        149                8
63        150                9
64        151                8
65        152                0
66        153                8
67        154                9
68        155                8
69        156                2
70        157                9
71        158                7
72        159                9
73        160                8
74        161                6
75        162                7
76        163                8
77        164                0
78        165                0
79        166                8
80        167                2
81        168                9
82        169                9
83        170                0

In [25]:
df2.to_excel(r'D:\python statistic\data\avg_week_result_OR 107.xlsx', index = False)